name = "actorx"
version = "0.0.0"
description = "ActorX - Reactive Extensions for Gleam using BEAM actors"
licences = ["MIT"]
repository = { type = "github", user = "dbrattli", repo = "ActorX" }
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.52.0"
gleam_otp = ">= 0.16.0"
gleam_erlang = ">= 0.35.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
